sassoftware/viya4-iac-aws

- docs/CONFIG-VARS.md
- docs/user/DockerUsage.md
- docs/user/TerraformUsage.md
Closes #53 - Cleans up typos and info in docs that needed updating.
> Doc updates fixing typos and info

- README.md
Closes #57 - Added info and link for deployment and SAS Viya 4.
> Added in SAS Viya 4 reference

- docs/CONFIG-VARS.md
- variables.tf
Check added to ensure correct kubernetes service account and custom role binding metadata name values.
> Added prefix validation check and doc updates

- main.tf
- modules/aws_vpc/outputs.tf
> (#75) use byo vpc cidr for nfs export and private cluster range

- docs/CONFIG-VARS.md
- docs/user/BYOnetwork.md
- locals.tf
- main.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
- modules/aws_vpc/variables.tf
- outputs.tf
- security.tf
- variables.tf
- vms.tf
> March Release - 3.3.0

- Dockerfile
Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/
> (IAC-529) added git share directive for viya4-iac-aws

- docs/CONFIG-VARS.md
push documentation only change to main branch
resolves #123
> (IAC-549) add missing .md suffix to TerraformAWSAuthentication.md file ref

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- locals.tf
- main.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_ebs_csi/variables.tf
- outputs.tf
- variables.tf
- versions.tf
* #156 
* #159 
* #160 
* #152 
* #139 
* #158 
* #162
> 5.2.0 - October 3, 2022

- locals.tf
In previous release `<prefix>` was added to node-names for the instances to use the `<prefix>`. However, this changes was propagated to all other resources in the node-group, which caused issue with resource `aws_iam_role` which has strict limit of 38 characters for `name_prefix`.
Adding Name tag in tag_specifications using the launch_template_tags now correctly adds the prefix to instance, network-interfaces and volumes instead of using your node-name. 
See launch_template_tags info in terraform EKS module [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/eks-managed-node-group/variables.tf#L247)
Created cluster using prefix with 21 characters. No issues were detected, Viya deployment on cluster was successful as well.
See internal ticket details.
> feat: (IAC-735): support longer length for PREFIX

- docs/CONFIG-VARS.md
- locals.tf
- variables.tf
> 5.3.0 - October 20, 2022

- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-defaults.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/output.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_vm/main.tf
- modules/aws_vm/outputs.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- outputs.tf
- security.tf
- variables.tf
- vms.tf
<h2>Feature</h2>
Added the option for customers to enable encryption for AWS Elastic Block Store (EBS) volumes and Elastic File System (EFS) from within the Terraform module. With this option, customers can control the encryption of their data directly from within the Terraform module, eliminating the need to go to the AWS management console and set up encryption manually.
<h2>Changes</h2>
The following elements were added to allow customers to enable EBS and EFS encryption:
* In the sub-directory './modules/aws_vm/variables.tf'
* Created a variable for enabling EBS encryption - set to false by default.
*  In the sub-directory './modules/aws_vm/main.tf'
* Set the 'encrypted' flag within 'aws_instance' and 'aws_ebs_volume' resources to 'var.enable_ebs_encryption'.
* In the root directory - …
> feat: (IAC-801): added AWS EBS and EFS encryption

- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-defaults.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/output.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_vm/main.tf
- modules/aws_vm/outputs.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- outputs.tf
- security.tf
- variables.tf
- vms.tf
> 5.5.0 - February 17, 2023

- container-structure-test.yaml
- docker-entrypoint.sh
- files/custom-data/additional_userdata.sh
- files/tools/iac_git_info.sh
- files/tools/iac_tooling_version.sh
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/output.tf
- modules/aws_autoscaling/variables.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_ebs_csi/variables.tf
- modules/aws_vm/main.tf
- modules/aws_vm/outputs.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- modules/kubeconfig/output.tf
- modules/kubeconfig/variables.tf
- outputs.tf
- security.tf
- variables.tf
- versions.tf
- vms.tf
> 5.6.1 - March 28, 2023

- .pre-commit-config_template.yaml
Add pre-commit tool .pre-commit-config_template.yaml configuration template file.
Additional steps are required to begin using the pre-commit tool with template file content.
See internal ticket description for steps on how to get started using the pre-commit tool.
> feat: (IAC-427) Add pre-commit tool config.yaml template

- .pre-commit-config_template.yaml
- files/custom-data/additional_userdata.sh
> 5.7.0 - April 5, 2023

- Dockerfile
- files/cloud-init/jump/cloud-config
- versions.tf
> 6.2.0 - June 26, 2023

- docs/CONFIG-VARS.md
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_vm/main.tf
- modules/aws_vpc/main.tf
- outputs.tf
- variables.tf
- versions.tf
> 7.0.0 - August 9, 2023

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
> 7.1.0 - August 18, 2023

- docs/CONFIG-VARS.md
- main.tf
- modules/aws_fsx_ontap/main.tf
- modules/aws_fsx_ontap/variables.tf
> 7.2.1 - September 8, 2023

- README.md
- docs/CONFIG-VARS.md
- docs/sas-updates.md
Updates SAS documentation links to use the parameterized format and documentation.sas.com host.
> docs: (IAC-1083) Update SAS doc links to use parameterized format

- docs/CONFIG-VARS.md
Update the `subnet` example in the config-vars.md to be single az only.
> docs: (IAC-1218) Update Subnet Example to be Single AZ Only

- linting-configs/.tflint.hcl
- modules/aws_autoscaling/outputs.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_vm/outputs.tf
- modules/kubeconfig/outputs.tf
- outputs.tf
> 8.0.1 - December 12, 2023

- modules/aws_autoscaling/main.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_vm/main.tf
> 8.1.1 - February 15, 2024

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
> 8.5.0 - August 29, 2024

- main.tf
- modules/aws_autoscaling/main.tf
> 8.5.1 - September 19, 2024

- outputs.tf
Eliminate racially-insensitive terminology:
- outputs:tf: replace internal uses of 'master' in strings
> fix: (PSKD-970) eliminate racially-insensitive terminology 

- .github/workflows/linter-analysis.yaml
- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- linting-configs/.hadolint.yaml
- linting-configs/.tflint.hcl
- locals.tf
- outputs.tf
- security.tf
- variables.tf
> 8.7.0 - January 17, 2025

- .github/workflows/linter-analysis.yaml
- Dockerfile
- README.md
- container-structure-test.yaml
- versions.tf
Updated binaries and Terraform providers/modules to reduce Critical and High CVEs reported in the docker image created for this project. Refer to the internal ticket for CVE details.
```markdown
Terraform
initial: 1.9.6
final: 1.10.5  (project min is 1.10.0)
awc-cli
initial: 2.17.58
final: 2.24.16
kubectl
initial: 1.30.6
final: 1.30.10
```
```markdown
registry.terraform.io/hashicorp/aws
Versions:
Initial: 5.68.0
Final: 5.89.0
Notes:
No breaking changes found that would affect resources used in this project, numerous new features/fixes.
Changelog: https://github.com/hashicorp/terraform-provider-aws/blob/v5.89.0/CHANGELOG.md
registry.terraform.io/hashicorp/cloudinit
Versions:
Initial: 2.3.5
Final: 2.3.6
Notes:
No breaking or function changes, release metadata changes only
Changelog: …
```
> chore: AWS - Security scan 2025.03 (PSKD-1402)

- test/default_unit_test.go
Couldn't figure out how to test `nfs_vm_admin`, but everything else is present
> test: Terratest NFS Tests

- CONTRIBUTING.md
- test/default_unit_test.go
> 8.9.1 - May 8, 2025

- docs/user/IAC-Overview.md
- examples/sample-input-byo.tfvars
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/outputs.tf
- modules/aws_autoscaling/variables.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_ebs_csi/variables.tf
- modules/aws_fsx_ontap/main.tf
- modules/aws_fsx_ontap/variables.tf
- modules/aws_vm/main.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- modules/kubeconfig/outputs.tf
- modules/kubeconfig/variables.tf
- security.tf
- variables.tf
- versions.tf
- vms.tf
Initial files with updated comments and direction
> docs: enhanced documentation
