- docs/CONFIG-VARS.md
- main.tf
- variables.tf
Some sites do not allow creation of IAM resources by automation tools.
This change documents the IAM Roles/Policies needed, and adds 2 variables that allow to pass pre-created Roles into the project.
Closes: #69
> support BYO IAM resources

- main.tf
Closes: #80 by allowing the module to create a db backup name that is unique
> (#80) use unique postgres final snapshot name

- examples/sample-input-minimal.tfvars
- main.tf
- variables.tf
Fixes: #77 
Added code which adjusted the `desired_capacity` of a node pool to `1` if the `autoscaling_enabled` variable is set to `true`. This allows the node pool to create at least 1 node for use. Since this is the `desired_cacaity` the value is honored upon node pool creation. However, in the spirit of auto scaling, if the nodes with with the `desired_capacity` value are not utilized the autoscaler will do its job.
> Added in logic to fix auto scaling node startup

- files/cloud-init/nfs/cloud-config
- main.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
The primary vpc cidr might not include the subnet cidrs.
And generally,we only need the public and private subnets to access the nfs server anway.
This fix also includes a couple of fixes to byo networking in the aws_vpc module.
Had to change the line endings in the cloud-config file
fixes #90
fixes #93
> use subnet cidrs in nfs export instead of primary vpc cidr

- outputs.tf
simplifies scripting of role updates
example for logging/monitoring:
aws iam attach-role-policy --policy-arn "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" --role-name "$(terraform output -raw cluster_iam_role_arn | cut -d/ -f2)"
aws iam attach-role-policy --policy-arn "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" --role-name "$(terraform output -raw worker_iam_role_arn | cut -d/ -f2)"
> add cluster iam role to output

- modules/aws_autoscaling/main.tf
Per [AWS CA Prerequisites](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html#ca-prerequisites) and the [worker_group_default.tags](https://github.com/sassoftware/viya4-iac-aws/blob/main/main.tf#L109) the condition of the CA IAM policy was not matching the applied tags, producing the following error:
```log
failed to delete empty node: failed to delete ip-192-168-xx-xx.ec2.internal: AccessDenied: User: arn:aws:sts::xxxxx:assumed-role/xxx-ns-cluster-autoscaler/xxxxxis not authorized to perform: autoscaling:TerminateInstanceInAutoScalingGroup on resource: arn:aws:autoscaling:us-east-1:xxxx:autoScalingGroup:xxx1f-xxxx-458a-ae1a-0788xxxx84f:autoScalingGroupName/xxx-ns-eks-xxxxx0000001b because no identity-based policy allows the …
```
> Fix AWS autoscaler IAM policy condition to match worker tags

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- variables.tf
- Verified using updated Dockerfile, cluster was deployed correctly using K8s v1.21.7 and Viya4 deployment on that cluster was successful
> (IAC-394) [AWS] update viya4-iac-aws from k8s 1.19 to 1.21

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- variables.tf
* (IAC-394) [AWS] update viya4-iac-aws from k8s 1.19 to 1.21
* Updated the version from 1.21.2 to 1.21.7 for uniformity among cloud clusters
> (IAC-394) [AWS] update viya4-iac-aws from k8s 1.19 to 1.21 (#119)

- README.md
Updating the README to include a section about the max_prepared_transactions. This only impacts people who use an external database instead of the internal postgres server. Viya requires the max_prepared_transactions to be at least 1024, but the external AWS postgres database defaults to 0. I included some steps on how to update the values manually.
> (IAC-158) Adding max_prepared_transactions section to README

- files/cloud-init/nfs/cloud-config
To address issue with raid device names being switched (initial value of md0 to mdXXX) between NFS VM restarts and or terraform (re)apply scenarios
> (IAC-349) Use device UUID in mount

- outputs.tf
typo fix in output.tf, label should be nfs_private_dns
> (IAC-563) fix nsf_private_dns typo in outputs

- versions.tf
Pin hashicorp/tls to v3.4.0 to work around this issue: https://issuemode.com/issues/hashicorp/terraform-provider-tls/109418411
More details in internal ticket.
After pinning the version, I was able to successfully create the infrastructure in AWS as well as perform a Viya deployment in the cluster.
> fix: (IAC-634) Pin hashicorp/tls to v3.4.0

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- variables.tf
Update the kubectl version being used to 1.22.10 and the k8s version in the sample input files to v1.22. Updated README and CONFIG-VARS doc.
See internal ticket for details and test artifacts
1. Used updated docker image to create clusters at 1.21, 1.22 and 1.23 K8s versions with successful deployments.
2. The updated kubectl version is now at 1.22.10 in the container
> feat: (IAC-544) AWS - support for k8s 1.23 and dropping 1.20

- locals.tf
Updates the node pool maps (default and user defined) in `locals.tf` to use `pre_bootstrap_user_data` rather than post so that the init script get run. The reason why pre needs to be used rather than post is because we do not specify a value for `ami_id`. See doc from AWS:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md#eks-managed-node-group
- Created a minimal .tfvars file that has a default and cas node pool.
Snippet:
```
kubernetes_version                      = "1.22"
default_nodepool_node_count             = 2
default_nodepool_vm_type                = "i3.8xlarge"
default_nodepool_custom_data            = "./files/custom-data/additional_userdata.sh"
node_pools = {
cas = {
"vm_type" = "i3.8xlarge"
"cpu_type"     = "AL2_x86_64"
"os_disk_type" = …
```
> fix: (IAC-700) change to pre_bootstrap_user_data for node pools

- docs/CONFIG-VARS.md
- variables.tf
Changes the default value for the `server_version` variable located within the `postgres_server_defaults` map to 13.
The user can specify any postgres version from 11 to 14.
Executed the following development test scenarios for each postgres version:
|PostgresSQL version scenario|Provider|K8s version|Cadence|Stable Deployment|input.tfvars server_version|RDS Installed (via TF) External Postgres version|
|---|---|---|---|---|---|---|
|PostgresSQL v11|AWS|1.23|fast:2020|Yes|11|db engine 11.16 (postgres 11.16 was installed with the current default of "11" in variables.tf)|
|v12|AWS|v1.22.11-eks|fast:2020|Yes|12|db engine 12.11|
|v13|AWS|v1.22.12-eks|fast:2020|Yes|left unspecified, 13 is the new default in variables.tf|db engine 13.7|
|v14|AWS|v1.22.12-eks|fast:2020|Yes|14|db engine 14.3|
> feat: (IAC-704) Update default postgresSQL server_version to v13

- docs/CONFIG-VARS.md
Update the `server_version` notes in `CONFIG-VARS.md` to be more clear about PostgreSQL requirements from SAS Viya.
> docs: (IAC-704) Update server_version notes

- locals.tf
Updated the code to include the `<prefix>-eks-<node_name>` to show up for the node names.
Verified the changes by creating cluster, instance names for the nodes were populated with prefix. See internal ticket for details.
> fix: (IAC-632) tfvars PREFIX not applied to host nodes for k8s/Viya

- docs/CONFIG-VARS.md
- variables.tf
Back down the Postgres version to v12 while waiting for 2022.10
Verified default version is set to 12
> feat: (IAC-731) Back down the Postgres version to v12

- main.tf
<h2 dir="auto">Changes</h2>
<p dir="auto">Modified the root main.tf; module.kubeconfig depends_on reference - to deal with the sas_iac_buildinfo creation/timeout failures.
</p>
<h2 dir="auto">Test</h2>
<p dir="auto">
See internal ticket for details and test artifacts:
</p>
<ol dir="auto">
<li>Used updated docker image and sample tfvars files to create sas_iac_buildinfo with success.</li>
</ol>
> (IAC_733)AWS - failed to create sas_iac_buildinfo

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- modules/kubeconfig/main.tf
- modules/kubeconfig/templates/kubeconfig-provider.tmpl
- variables.tf
- versions.tf
Starting from Kubernetes version `1.24.0` service account token is not automatically generated, thus it has to be created separately. The following resources were updated by the provider `hashicorp/kubernetes` to handle this change in `v2.13.0`: `d/kubernetes_service_account`, `r/kubernetes_default_service_account`, `r/kubernetes_service_account`. For Kubernetes clusters running v1.24+ `default_secret_name` will be empty. A warning message will be printed once any of the above resources are in use. 
* To support 1.24+ Kubernetes version in EKS, a secret is manually created for the service account
* The default K8s value is updated from 1.22 to 1.23
* The default kubectl value is updated from 1.22.10 to 1.23.8
* Updated `hashicorp/kubernetes` to 2.13.0
* An update was made to …
> feat: (IAC-655) EKS Add Support for K8s 1.24

- README.md
- docs/CONFIG-VARS.md
- docs/sas-updates.md
- docs/user/AdvancedTerraformUsage.md
Updating the SAS Viya name in the documentation
The repo's "About" section will also need to change as part of this PR, since that's not controlled by the code I'll put the updated content here. Please review this as well.
>This project contains Terraform configuration files to provision infrastructure components required to deploy SAS Viya platform products products on Amazon AWS.
> docs: (IAC-864) Update SAS Viya name in documentation

- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-defaults.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/output.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_vm/main.tf
- modules/aws_vm/outputs.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- outputs.tf
- security.tf
- variables.tf
- vms.tf
<h2 dir="auto">Changes</h2>
<p dir="auto">
Changed variables "cluster_iam_role_name" and "workers_iam_role_name" to "cluster_iam_role_arn" and "workers_iam_role_arn" and added definitions for the variables as "iam_role_arn" to the EKS module in the root "main.tf" configuration file. This allows the customer to provide their own IAM roles for the EKS cluster and worker nodes, addressing the issue of undefined "role_arn".
</p>
<h2 dir="auto">Test</h2>
<p dir="auto">
See internal ticket for details and test artifacts:
</p>
1. Created custom IAM roles for the EKS cluster and node group for testing purposes.
2. Implemented the changes mentioned above - locally.
3. Implemented the use of custom IAM roles for the EKS cluster and worker nodes by: 
* Adding the ARNs of the IAM roles to the …
> fix: (IAC-551): fixed iam_role_arn not set when a user is bringing their own infra items in AWS

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- modules/aws_autoscaling/main.tf
- variables.tf
Since the SAS Viya Platform will be supporting K8s 1.23, 1.24, and 1.25 in March as part of the 2023.03 cadence, the kubectl and cluster_version version is being changed to 1.24.10 so that it's within the +/- 1 range of the supported versions. 
This PR also includes an update to the policy to add support for the new default `CLUSTER_AUTOSCALER_CHART_VERSION` (9.25.0) used for K8s 1.25+ clusters in viya4-deployment. This policy update was additive so `CLUSTER_AUTOSCALER_CHART_VERSION` (9.9.2) that is being used for <1.25 clusters still functions.
The PR where the `CLUSTER_AUTOSCALER_CHART_VERSION`  update was made is https://github.com/sassoftware/viya4-deployment/pull/399 and will be released as part of viya4-deployment:6.3.0. In case a user uses version 5.5.0 of viya4-iac-aws or earlier …
> feat: (IAC-903): add K8s 1.25 support, set kubectl default to 1.24

- files/custom-data/additional_userdata.sh
Remove cloud-init incompatible copyright character from first line of custom-data cloud-init script.
shellcheck linter removed end of line spaces on lines 5 & 7.
The copyright character u'\xa9' is not a valid character for cloud-init scripts.
Prior to update
|Scenario|Provider|K8S version|Order|terraform-input.tfvars|Process|Notes|
|-|-|-|-|-|-|-|
|1|AWS|1.24|n/a|sample-input-ha.tfvars|terraform apply -auto-approve -var-file sample-input-ha.tfvars -var location=us-west-2 -var prefix=davhou-507ha|Terraform apply fails with the failure to join kubernetes cluster error msg below |
```
Error: error waiting for EKS Node Group (davhou-507ha-eks:cas-20230330190117797700000029) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred: i-025a206ff6b734692: …
```
> fix: (IAC-974) CAS instance fails to join kubernetes cluster using sample-input-ha.tfvars

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
SAS Viya Platform will support K8s 1.24-1.26 in cadence v2023.05. This change updates the default kubernetes version to `1.25` and kubectl to `1.25.8`.
Verify SAS Viya Platform deployment is successful for the following scenarios, see details in internal ticket:
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method| Result |
|:----|:----|:----|:----|:----|:----|:----|
|1|OOTB|AWS|Stable 2023.04|1.24.11|docker, DO: false| Successful |
|2|OOTB|AWS|Stable 2023.04|1.25.7|ansible (staging), DO: true| Successful |
|3|OOTB|AWS|fast:2020|1.26.2|docker (test-1002), DO: false| Successful|
> feat: (IAC-980) add K8s 1.26 support, set kubectl default to 1.25

- README.md
Updated the link in 'README.md' for the Viya platform deployment process, to redirect to AWS.
> doc: (IAC-948) fixed viya4-iac-aws doc points to AWS EKS doc

- files/cloud-init/jump/cloud-config
When viya4-iac-aws creates a new jump server vm, it sets file ownership and permissions for the mounted NFS location which allows Viya services to initialize successfully. Importantly, the file system settings should only be applied once and not repeatedly in the event that the jump vm is destroyed and recreated in the same cluster. This change checks if the `${jump_rwx_filestore_path}/pvs` folder already exists and skips creating the folder and recursively setting ownerships and permissions if it does. If the jump vm is being created for the first time when the pvs folder is absent, creating the folder and setting permissions and ownership will occur an initial time and not thereafter.
Steps:
- Have an existing AWS cluster that was created using IaC
- Verify infrastructure created …
> fix: (IAC-1068) IAC jumpvm cloud-init, only set folder permissions and ownership initially

- Dockerfile
- versions.tf
- Update 5 rpms with identified high CVEs
- Update hashicorp/tls provider to 4.0.4 to remediate high CVEs present in the current version (no references to any of the resources with breaking changes are in use, otherwise just bug fixes and enhancements compared to the current provider version)
See internal ticket for description of high CVEs still present with remediation plans.
- Create k8s 1.26 AWS cluster using sample-input.tfvars.
- Deploy Viya 2023.05 stable to the cluster and verified a stable deployment, successful administrator login to Viya application.
|Scenario| Method| Provider| K8s version| Cadence| Notes |
|-|-|-|-|-|-|
|1| docker| AWS | v1.26.5-eks | 2023.05:stable | external postgres|
> fix: (IAC-1036) AWS - Security scan remediation for High CVEs

- docs/CONFIG-VARS.md
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_vm/main.tf
- modules/aws_vpc/main.tf
- outputs.tf
- variables.tf
- versions.tf
- add new `aws_shared_credentials_files` input variable
- add CONFIG-VARS.md text indicating `aws_shared_credentials_file` input variable has been deprecated and will be removed in a future release
- add precondition check and error message to warn against configuring both `aws_shared_credentials_file` and `aws_shared_credentials_files` input variables at the same time and encourage the use of the newer variable instead of the deprecated variable.
- update required child module provider versions to 5.0+
- required `aws_eip` resource attribute changes
| Scenario | `create_static_kubeconfig` | `aws_shared_credentials_file` | `aws_shared_credentials_files` | Plan results |
|----------|--------|-------|--------|-----------------------------------------------|
| 1 | false | not specified | not …
> feat: (IAC-722) update terraform-aws-eks module version

- main.tf
Testing the updates in https://github.com/sassoftware/viya4-iac-aws/pull/218 revealed that manually setting an external postgres administrator_password resulted in a failing Viya deployment due to an unexpected postgres adminstrator_password value in terraform.tfstate
The [4.0 upgrade guide](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/UPGRADE-4.0.md) for the terraform-aws-rds module points out that the create_random_password variable is now set to `true` while it was previously set to `false`.
- Update iac-aws to restore the previous setting of create_random_password to `false`. Doing so allows for manually setting an adminstrator_password as before, as well as restoring the documented default administrator_password in the event that no administrator_password is …
> feat!: (IAC-722) restore previous aws-rds module behavior, set create_random_password=false

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
* Update the default `kubectl` version in the Dockerfile and README to 1.26.7
* Update the default `kubernetes_version` in CONFIG-VARS.md to 1.26, reflecting the change made in variables.tf
* Update the default `kubernetes_version` in the example files to 1.26. 
| Scenario | Task | Provider | kubernetes_version      | kubectl version | order  | cadence        | notes             |
|----------|------|----------|-------------------------|-----------------|--------|----------------|-------------------|
| 1        | OOTB | AWS      | 1.26 (v1.26.7-eks)      | 1.26.7          | ****** | stable:2023.06 | docker, deploy command, successful deployment and login to Viya ingress as viya_admin |
| 2        | OOTB | AWS      | 1.27 (v1.27.4-eks)      | 1.26.7          | n/a    | n/a            | not …
> feat: (IAC-1123) Add support for k8s 1.27, set kubectl default to 1.26

- docs/CONFIG-VARS.md
- main.tf
- modules/aws_fsx_ontap/main.tf
- modules/aws_fsx_ontap/variables.tf
- only create and attach required FSx policy document when FSx for NetApp ONTAP file system is configured with storage_type=ha, storage_type_backend=ontap
- update the documented default value for aws_fsx_ontap_file_system_throughput_capacity input variable
- remove unused variable reference
| Scenario | Base Policy includes iam:AttachUserPolicy & iam:DetachUserPolicy | storage_type | storage_type_backend | Notes |
|-|-|-|-|-|
|1| true | ha | efs | successful cluster creation with EFS file system, no FSx policy doc created |
|2| true | ha | ontap | successful cluster creation, FSx policy doc created and attached to user |
|3| false | ha | undefined | successful cluster creation with EFS file system, no FSx policy doc created or attached, no terraform attach policy error |
> fix: (IAC-1165) Error: attaching policy msg occurs with a previously working tfvars file

- locals.tf
Update the naming of the node pool IAM roles. Before this change the roles were an autogenerated name based off just the node pool name which made them hard to track, especially if you are working with multiple clusters. This change makes it so that the name will now include the `prefix` value in additional to the node names when the roles are created.
e.g.  the roles are now `cas-eks-node-group-[timestamp-unique]` -> `my-cool-prefix-cas-eks-node-group`
This is not a breaking change either, if you rerun apply using this PR using an earlier release the node pool IAM roles will just be replaced with ones with the updated names and associated with the existing node pools.
| Scenario | Provider | K8s Version         | Order  | Cadence   | Notes …
> fix: (IAC-923) Update Node Pool IAM Role Names to Include Prefix

- docs/CONFIG-VARS.md
- examples/sample-input-singlestore.tfvars
- files/policies/devops-iac-eks-policy.json
- main.tf
- variables.tf
In order to line up with the recommendations from the SAS Viya Platform Operations documentation we are updating the code base so that when EKS node groups are created they will be placed in a single-AZ rather than spanning over multiple-AZs. This feature is controlled by the new variable `enable_multi_zone` which by default will be set to false, resulting in the node groups being a single subnet in a single-az.
This is considered a breaking change single since users who initially created their infrastructure with viya4-iac-aws:7.2.1 or earlier, and want to use the new version to make adjustments to their infrastructure will now have their node groups moved to a single-az. If they have a stopped Viya deployment they were planning on starting after the infrastructure updates, they will …
> feat!: EKS Node Pool Subnets to use Single AZ by Default

- .github/workflows/linter-analysis.yaml
- linting-configs/.tflint.hcl
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/output.tf
- modules/kubeconfig/outputs.tf
- modules/kubeconfig/variables.tf
Updated the linting workflow config so that branches named with the path pattern (e.g. `feat/1078`) will also have pipeline automatically triggered for them.
Additionally, updated the linting workflow config so that `tflint` will now get run against the terraform files under `./modules`. In doing so additional formatting warnings appeared which was also resolved.
No functional changes, just formatting.
| Scenario | Provider | K8s Version         | Notes                     |
|----------|----------|---------------------|---------------------------|
| 1        | AWS      | v1.26.7-eks-2d98532 | Infra creation smoke test |
| 2        | AWS      | v1.26.7-eks-2d98532 | Infra creation smoke test, retest |
> feat: (IAC-1078) Linting Updates and Code Formatting

- docs/CONFIG-VARS.md
- examples/sample-input-singlestore.tfvars
- main.tf
- variables.tf
Reverts the EKS Single AZ changes from #234
| Scenario | Provider | Summary     | From                   | To  | K8s Version         | Order  | Cadence   | Notes                                     |
|----------|----------|-------------|------------------------|-----|---------------------|--------|-----------|-------------------------------------------|
| 1        | AWS      | Revert #234 | viya4-iac-aws: PR #237 | N/A | v1.26.8-eks-43840fb | * | fast:2020 | previous multi-az behavior observed again |
> fix: (IAC-1174) Revert the Single AZ Changes

- docs/CONFIG-VARS.md
- main.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
- modules/aws_vpc/variables.tf
- variables.tf
In order to line up with the recommendations from the SAS Viya Platform Operations documentation we are updating the code base so that when EKS node groups are created they will be placed in a single-AZ rather than spanning over multiple-AZs. This feature is controlled by an update to the `subnets` and `subnets_ids` map by adding a new key `control_plane` to allow finer control for subnet assignment. CIDRs/IDs added to the `control_plane` list will be used for only for the control plane when creating the EKS cluster, [AWS requires](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html) that there are at least two CIDR ranges provided in different AZs, both ranges must have at least 6 addresses. The existing `private` CIDR list will now no longer be shared with the control …
> feat!: (IAC-1174) EKS Node Pool Subnets to use Single AZ by Default

- docs/CONFIG-VARS.md
- locals.tf
- main.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/variables.tf
- outputs.tf
- variables.tf
Allows users the ability to specify which AZs that the subnet gets created in with the new `subnet_azs` variable.
Similar to the existing `subnets` the map lets to set the name of the subnet along with zones will be used during creation
```terraform
subnet_azs = {
"private"       : ["us-east-2c"],
"control_plane" : ["us-east-2c", "us-east-2b"],
"public"        : ["us-east-2a", "us-east-2b"],
"database"      : ["us-east-2a", "us-east-2b"]
}
```
So if your defined subnets as so in your .tfvars
```terraform
{
"private" : ["192.168.0.0/18"], 
"control_plane" : ["192.168.130.0/28", "192.168.130.16/28"],
"public" : ["192.168.129.0/25", "192.168.129.128/25"],
"database" : ["192.168.128.0/25", "192.168.128.128/25"]
}
```
for `"control_plane" : ["192.168.130.0/28", "192.168.130.16/28"]`, the first …
> feat: (IAC-367) Allow Ability To Specify Which Availability Zones the Subnets Get Created In

- linting-configs/.tflint.hcl
- main.tf
Update the code to re-enable `terraform_deprecated_lookup` linting rules and resolve any warnings
doc: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_lookup.md
Created infrastructure and ensured the `sas-iac-buildinfo` was present
```
viya4-iac-aws$ kubectl get cm -n kube-system sas-iac-buildinfo -o yaml
apiVersion: v1
data:
git-hash: f0037f49843ca9fad9bcf9bae6853c90750303e9
iac-tooling: docker
terraform: |
version: "1.4.5"
revision: null
provider-selections: {"registry.terraform.io/hashicorp/aws":"5.4.0","registry.terraform.io/hashicorp/cloudinit":"2.3.2","registry.terraform.io/hashicorp/external":"2.3.1","registry.terraform.io/hashicorp/kubernetes":"2.20.0","registry.terraform.io/hashicorp/local":"2.4.0","registry.terraform.io/ha …
```
> chore: (IAC-1227) enable terraform_deprecated_lookup

- locals.tf
Using a byo_network_scenario=2 configuration when `cluster_api_mode=public` and where the IaC client VM is running within the byo_network configured VPC, the IaC client VM requires connectivity to the EKS cluster API server endpoint as it does for other configurations. The `cluster_endpoint_private_access_cidrs` variable can be used to specify either an IP address or CIDR range for the IaC VM client, but the existing behavior prevents the creation of the required security group ingress rule when `cluster_api_mode=public`. Given that we'd like the IaC client VM network configuration described above to access the EKS cluster API server endpoint, allowing values to be set for `cluster_endpoint_private_access_cidrs` and creating the SG ingress rule should be allowed with `cluster_api_mode` …
> fix: (IAC-1240) cluster_api_mode=public requires ingress rules for API server's private IP address

- container-structure-test.yaml
Terraform binary and awc-cli version updates in PR #246 required version bumps in container-structure-test.yaml file for github action executed for PRs targeting the main branch.
> chore: (IAC-1190) Bump container test expected versions for terraform and aws-cli

- linting-configs/.tflint.hcl
- modules/aws_autoscaling/outputs.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_vm/outputs.tf
- modules/kubeconfig/outputs.tf
- outputs.tf
Enable the `terraform_documented_outputs` `tflint` rule and update the `output.tf` files to ensure each output has a description.
Ran through infrastructure creation with this PR, there are no functional changes just adding descriptions
> chore: (IAC-1119) add a description for all Terraform outputs without one

- linting-configs/.tflint.hcl
Remove the explicit definition of `terraform_documented_outputs`. This `tflint` rule is enabled by default so we can remove it from `.tflint.hcl` to clean things up.
> chore: (IAC-1292) remove terraform_documented_outputs explicit definition

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- main.tf
- variables.tf
- Updated default kubernetes_version in variables.tf to 1.27
- Updated the default kubernetes_version in the example files to 1.27.
- Updated the default kubectl version in the Dockerfile to 1.27.9 (currently the latest)
|Scenario|Provider|kubernetes_version|kubectl version|order|cadence|notes|
|-|-|-|-|-|-|-|
|1|AWS|1.26 (v1.26.11-eks)|1.27.9|**|stable:2023.12|docker, deploy command|
|2|AWS|1.27 (v1.27.8-eks)|1.27.9|**|stable:2023.10|docker, deploy command|
|3|AWS|1.28 (v1.28.4-eks)|1.27.9|**|stable:2023.12| not yet supported |
> feat: (IAC-1265) AWS - Support K8s 1.28 in Viya 2024.02

- README.md
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_ebs_csi/main.tf
- modules/kubeconfig/main.tf
- versions.tf
Updates 3rd party dependencies to resolve the security vulnerabilities. Users of the Dockerfile will automatically have these updated dependencies installed, and users who directly run this project on the host will need to update the dependencies themselves.
Update summary:
- terraform 1.6.3 -> 1.6.6
- updates google.golang.org/grpc from v1.56.1 to v1.59 to remediate High CVE-2023-44487
- updates golang.org/x/net from v0.8.0 to v0.19.0, remediating multiple high CVEs
- hashicorp/aws from 5.25.0 to 5.31.0
- bug fixes, features and enhancements, 5.27.0 includes an update to the AWS SDK for Go v2, provider changes should be transparent to users
- hashicorp/cloudinit from 2.3.2 to 2.3.3
- no functional changes, does include dependency updates to address upstream CVEs
- hashicorp/external from …
> feat: (IAC-1259) AWS - Security scan 2024.01

- container-structure-test.yaml
Terraform binary version update in PR #261 required version bump in container-structure-test.yaml file for github action executed for PRs targeting the main branch.
> chore: (IAC-1259) Bump container test expected versions for terraform

- modules/aws_autoscaling/main.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_vm/main.tf
Fix for resources that did not have tags set for them. The following resources will now have tags applied:
* cluster-autoscaler IAM Role
* ebs-csi IAM role
* Jump vm root volume
* NFS vm root volume
| Scenario | Provider | K8s Version         | Order  | Cadence   | Notes                                                                            |
|----------|----------|---------------------|--------|-----------|----------------------------------------------------------------------------------|
| 1        | AWS      | v1.27.9-eks-5e0fdde | ****** | fast:2020 | tags applied to resources                                                        |
| 2        | AWS      | v1.27.9-eks-5e0fdde | N/A    | N/A       | 8.1.0 initial infra creation, apply again with PR code, resources had tags added |
> fix: (IAC-922) Assign tags to resources missing them

- .github/workflows/container-structure-test.yml
Currently, the container structure test github action only runs on pushes and pull requests to the main branch. That is too late and can result in acceptance test failures when creating the staging->main PR when it's time to create a new release. It would be more helpful for that acceptance test to run earlier. Adding a trigger to run this same test for pull requests to staging branch also which will allow us to find any failures earlier in our workflow.
Screen capture of the checks run below indicate that the container acceptance tests ran for this PR when it was created and targeted to merge into staging which was the goal of this change.
> chore: (IAC-1330) Update container structure workflow to run acceptance test for PRs targeting staging branch

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
* Updated the default `kubernetes_version` in the example files to 1.28.
* Updated the default `kubectl` version in the Dockerfile to 1.28.7 (currently the latest)
| Scenario | Provider | K8s Version          | kubectl | Order  | Cadence   | Notes                                      |
|----------|----------|----------------------|---------|--------|-----------|--------------------------------------------|
| 1        | AWS      | v1.29.1-eks-b9c9ed7  | 1.28.7  | * | fast:2020 | OOTB                                       |
| 2        | AWS      | v1.28.7-eks-b9c9ed7  | 1.28.7  | * | fast:2020 | OOTB                                       |
| 3        | AWS      | v1.27.11-eks-b9c9ed7 | 1.28.7  | * | fast:2020 | OOTB - overwrite kubectl version in the DO |
> feat: (IAC-1376) Add Support for K8s 1.29

- container-structure-test.yaml
- docker-entrypoint.sh
- files/tools/iac_git_info.sh
- files/tools/iac_tooling_version.sh
- locals.tf
- main.tf
- modules/aws_autoscaling/main.tf
- modules/aws_autoscaling/outputs.tf
- modules/aws_autoscaling/variables.tf
- modules/aws_ebs_csi/main.tf
- modules/aws_ebs_csi/outputs.tf
- modules/aws_ebs_csi/variables.tf
- modules/aws_fsx_ontap/main.tf
- modules/aws_fsx_ontap/outputs.tf
- modules/aws_fsx_ontap/variables.tf
- modules/aws_vm/main.tf
- modules/aws_vm/outputs.tf
- modules/aws_vm/variables.tf
- modules/aws_vpc/main.tf
- modules/aws_vpc/outputs.tf
- modules/aws_vpc/variables.tf
- modules/kubeconfig/main.tf
- modules/kubeconfig/outputs.tf
- modules/kubeconfig/variables.tf
- outputs.tf
- security.tf
- variables.tf
- versions.tf
- vms.tf
Updated Copyright information in all the applicable files.
> docs: (IAC-1411) Updated copyright range to 2024

- locals.tf
- Update the k8s.io/cluster-autoscaler key and tag values for the default_node_pool and the user_node_pool to align them with what is expected.
- Verify that the EC2 node instances created by the Auto Scaling Group include the two updated k8s.io/cluster-autoscaler key and tag values made under this PR. Details are included in the testing assets file available in the internal ticket.
| Provider | K8S Version | TF input file | region | Notes |
|-|-|-|-|-|
| AWS | 1.28 | terraform-input-byongp3.tfvars | us-west-1 | Both updated k8s.io/cluster-autoscaler/* Tag key and value pairs are present after cluster create as desired. See assets zip file on internal ticket for command output details and Terraform input file content.
> fix: (IAC-1380) AWS Autoscaling Launch Template Tags Incorrect

- Dockerfile
- container-structure-test.yaml
Update Terraform, AWS cli and kubectl versions to remediate the High security vulnerabilities reported by the most recent Aqua Scan, see full results in the internal ticket.
Final scan result has: 0 Critical, 0 High security vulnerabilities.
> feat: (IAC-1472) AWS - Security scan 2024.06

- variables.tf
Revise a previously made update to the type for the s3 private endpoint used in private EKS clusters.
Issue Description: Be default, the viya4-iac-aws project should create the s3 private endpoint with a type of "interface". Currently, viya4-iac-aws creates a s3 private endpoint with a type of "gateway" for use with private EKS clusters. [IAC-759](https://rndjira.sas.com/browse/IAC-759) incorrectly advised that the s3 private endpoint should be changed to a type of "gateway". That could work, but additional more complex routing configuration not already present in the project would be required in order for the s3 private endpoint to work with a type "gateway".
Additional testing since then has shown that the existing "interface" type for the s3 private endpoint is sufficient and works as …
> fix: (PSKD-494) AWS - private endpoint type for S3 should be of type Interface

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- variables.tf
**Changes**
- 	Updated the default kubernetes_version in the example files to 1.29.
- 	Updated the default kubectl version in the Dockerfile to 1.29.7 (currently the latest)
**Tests**
Scenario | Provider | K8s Version | kubectl | Order | Cadence | Notes
-- | -- | -- | -- | -- | -- | --
1 | AWS | 1.28.11-eks-db838b0 | 1.29.7 | * | fast:2020 | OOTB
2 | AWS | 1.29.6-eks-db838b0 | 1.29.7 | * | fast:2020 | OOTB
3 | AWS | 1.30.2-eks-db838b0 | 1.29.7 | * | fast:2020 | OOTB - Overwrite kubectl version in the DO. Some pods and PVCs were stuck in Pending. I believe this is due to PSKD-434
> feat: (PSKD-517) Add Support for K8s 1.30

- modules/aws_autoscaling/main.tf
Reverts sassoftware/viya4-iac-aws#300
> Revert "fix: (PSKD-678) viya4-aws-iac creates an incomplete IAM policy for the autoscaler Service Account"

- modules/aws_autoscaling/main.tf
We've updated the IAM cluster-autoscaler policy to address an unwanted error message
kubectl -n kube-system logs -l 'app.kubernetes.io/instance=cluster-autoscaler' --tail=-1 | grep '^E'
E0604 20:35:15.324713 1 aws_manager.go:308] Failed to get labels from EKS DescribeNodegroup API for nodegroup cas-202401... in cluster viya-... because AccessDeniedException: User: arn:aws:sts::7...
/viya-...-cluster-autoscaler/17... is not authorized to perform eks:DescribeNodegroup on resource: arn:aws:eks:ca-central-1:7...:nodegroup/viya.../cas-202401...-dea0-52....
> fix: (PSKD-678) viya4-aws-iac creates an incomplete IAM policy for the autoscaler Service Account redo

- main.tf
From https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html
> Starting with 1.30, Amazon EKS no longer includes the default annotation on the gp2 StorageClass resource applied to newly created clusters. This has no impact if you are referencing this storage class by name. You must take action if you were relying on having a default StorageClass in the cluster.
The changes made here are helping to mitigate issues arising from the last sentence above.
Internal testing of the proposed changes have been positive.
> (PSKD-434) AWS no longer has a default storage class with K8s 1.30

- Dockerfile
- linting-configs/.tflint.hcl
"chmod" command in Dockerfile moved after the "terraform init" command to allow for overriding the default local backend.
> fix: permissions set in dockerfile (PSKD-903)

- variables.tf
This PR simply adds gp3 to the validation condition in variables.tf, making gp3 a valid option for `default_nodepool_os_disk_type`. The default of gp2 is preserved.
> feat: allow gp3 disk type in default_nodepool_os_disk_type

- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- modules/aws_vm/variables.tf
- variables.tf
- Update all example/sample*.tfvars files instance types to comply with SAS Worldwide Sizing recommendations
- Update project defaults for vms and eks node instance types to match SAS Worldwide Sizing recommendations
- Update the default external Postgres disk size to 128 GB per SAS Worldwide Sizing recommendation
- Fix Postgres `storage_size` configuration variable units reference to indicate GB 
- Used the updated sample-input.tfvars file to successfully provision a new EKS cluster with IaC AWS.
- Verified that the resulting VM and EKS node EC2 instance types used were those specified as a project default or present in the sample-input.tfvars file.
- Verified that the initial external Postgres disk size is 128 GB instead of 50 GB.
> chore: Update AWS instance types to align with WW Sizing recommendations (PSKD-650)

- examples/sample-input-byo.tfvars
- test/default_unit_test.go
- Add the `cluster_security_group_id` and `workers_security_group_id` configuration variables and comments to the sample-input-byo.tfvars file. The resulting three security group ids complete the set of pre-existing security group ids that can be configured when using a bring your own network (BYON) scenario with IaC AWS.
- Update the expected defaultNodepoolVmType to fix the default value test that began failing with changes implemented in PR #330
> docs: Add additional security_group_ids to sample-input-byo.tfvars (PSKD-1292)

- docs/CONFIG-VARS.md
- Add missing comma to the external postgres servers parameters value list and include a working example value that can be used to set the `shared_preload_libraries` parameter correctly.
Using the first parameters value list in the updated parameters example, I was able to confirm the set of `shared_preload_libraries` for the Postgres instance was set properly by examining the RDS postgres instance parameter_group in the AWS Portal. If I remove the required comma between the name/value pair, I was able to duplicate the same error message documented in the description for the internal ticket.
The shared_preload_libraries value captured from the AWS Portal for the created external Postgres instance indicates that the expected value has been set correctly.
```code
Name, Value, Apply type, …
```
> docs: Correct parameter value syntax for external postgres servers (PSKD-1439)

- security.tf
- test/default_unit_test.go
Update the security group so that it adds the SSH ingress rules for the VMs. This is fixing a regression from the `8.7.0` release.
I've verified that the Jump VM and NFS VM have a SSH ingress rule for each IP in my default_public_access_cidrs.
> fix: restore ssh ingress rule for vms

- .github/dependabot.yml
- .github/workflows/container-structure-test.yml
- .github/workflows/conventional-commits.yml
Modify workflows previously targeting 'staging' to now target the 'main' branch.
> chore: update workflows to point to main

- README.md
This PR updates to use a specific tagged release of the viya4-iac-aws module, instead of referencing the main branch.
> docs: update README to suggest release tags

- Dockerfile
- README.md
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-custom-data.tfvars
- examples/sample-input-gpu.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input-singlestore.tfvars
- examples/sample-input.tfvars
- files/custom-data/additional_userdata.sh
- test/defaultplan/default_unit_test.go
- test/defaultplan/eks_test.go
- test/nondefaultplan/nodepool_test.go
- variables.tf
- Updated the IaC code to support Kubernetes version 1.32, as part of enabling support for v1.33.
- Added use of kubectl 1.32.6 binary to ensure compatibility when deploying clusters on Kubernetes 1.33.
- Changed the default cpu_type to AL2023_x86_64_STANDARD:
- AWS has announced end-of-life (EOL) for Amazon Linux 2 (AL2) on November 26, 2025.
- AL2023 is fully supported, compatible with cloud-init, and allows us to keep our existing Terraform custom_data scripts (with minor changes like replacing yum with dnf).
- This ensures our clusters remain deployable and supported beyond AL2 EOL.
|Scenario|Method|K8s cluster version|Postgres|cadence|Deployment Operator|Notes|
|-|-|-|-|-|-|-|
|1|Docker|v1.31.x|External|n/a|Deployment operator Enabled|Successful Viya deployment; all pods running; …
> feat: add AWS 1.33 support (PSCLOUD-73)
